import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/components/counter/providers';
import Header from '@/components/header/Header';
import Footer from '@/components/footer';
import Chatbot from '@/components/Chatbot';

export const metadata: Metadata = {
    title: 'Website TGDD',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex flex-col items-center">
                <Providers>
                    <Header />
                    <div className="flex justify-center w-full max-w-[1440px] px-4">
                        <main className="flex-1 max-w-[1200px] w-full">{children}</main>
                    </div>
                    <Chatbot className="fixed bottom-4 right-4" />
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
